### ISSUE TITLE
4.44 编译不过

### ISSUE THREAD

**Issue by 360060316** [kalu-github/module_mediaplayer#10]
报错 libavfilter/dnn_filter_common.c:36: error: undefined reference to 'ff_get_dnn_module'

**Comment by xiaodatao2007** [comment]
怎么编译的，有没有ijk官网类似介绍，一步步执行。

**Comment by zhxacg** [comment]
> 怎么编译的，有没有ijk官网类似介绍，一步步执行。

cmake ndk windows环境编译

**Comment by zhxacg** [comment]
> 报错 libavfilter/dnn_filter_common.c:36: error: undefined reference to 'ff_get_dnn_module'

src => main => cpp => ffmpeg4 => lib => ** => *.zip, 这个文件解压
