### ISSUE TITLE
关于ijkplayer问题

### ISSUE THREAD

**Issue by niuyunwang** [kalu-github/module_mediaplayer#11]
作者您好，最近使用播放器，发现点问题给您反馈下：
1.ijkplayer播放器长时间暂停在恢复黑屏（短暂暂停在播放没问题），用pause暂停，start恢复播放
2.关于截屏问题，希望可以支持下截屏，用surfaceview去做截图非常麻烦。
最后感谢作者提供的开源项目

**Comment by niuyunwang** [comment]
还有一个问题忘记说了，在播放器release(）频繁的时候很容易ANR

**Comment by zhxacg** [comment]
手动 release() 前先 stop()
