### ISSUE TITLE
大佬，能否增加x64的ijk的so库

### ISSUE THREAD

**Issue by wanbanjiesan** [kalu-github/module_mediaplayer#2]
自己环境编译总报错，还不知道怎么解决，Goole Play要求必须支持64位，需要x64的so库，大佬能否编译下，在下谢谢大佬了！！！

**Comment by zhxacg** [comment]
https://github.com/kalu-github/ijkplayer-k0.8.8-ff4.0， 自己就能编译x64

**Comment by zhxacg** [comment]
加了

**Comment by wanbanjiesan** [comment]
非常感谢大佬，谢谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kalu-github/module_mediaplayer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月2日(星期三) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kalu-github/module_mediaplayer] 大佬，能否增加x64的ijk的so库 (Issue #2)





 
加了
