### ISSUE TITLE
請問 full 跟 lite 差別在哪

### ISSUE THREAD

**Issue by FongMi** [kalu-github/module_mediaplayer#3]
解碼器數量會差很多嗎

**Comment by FongMi** [comment]
有興趣幫我的殼搞 ijk 的 so 嗎
目前是用 https://github.com/LZ9/MMSPlayer 這個庫

**Comment by FongMi** [comment]
請問為什麼缺少 libijksdl.so ?

**Comment by zhxacg** [comment]
lite删掉了，现在只保留full

**Comment by zhxacg** [comment]
libijksdl.so\libijkplayer，合并了1个libffmpeg-player.so

**Comment by FongMi** [comment]
了解，謝謝。
