### ISSUE TITLE
這個網址不能播

### ISSUE THREAD

**Issue by FongMi** [kalu-github/module_mediaplayer#4]
https://rongxingvr11.rx9696mv.com:8866/0nwDOqrZ1VmZkSOw7rYKjD8BgeUeLFXqzUuGmFb3akj9M4nEzz92_R70UgP8OiryFEXVLEgWROMM_u8Lyiq8lw/RongXingVR.m3u8

**Comment by FongMi** [comment]
![image](https://user-images.githubusercontent.com/3471963/203458762-1901ba24-774a-4a8b-9f18-31cef378d32a.png)

**Comment by FongMi** [comment]
網址已失效，是不是沒有加入相對應的解碼？

**Comment by zhxacg** [comment]
超高分辨率，建议exo硬解

**Comment by zhxacg** [comment]
不支持vr视频
