### ISSUE TITLE
您好支持rtsp udp传输吗？

### ISSUE THREAD

**Issue by codesdt** [kalu-github/module_mediaplayer#5]
您好支持rtsp udp传输吗？
我们是公司局域网内，使用rtsp 播放  udp传输协议，多播

**Comment by zhxacg** [comment]
支持

**Comment by codesdt** [comment]
直接github上下载下来吗？然后运行？

kalu ***@***.***> 于2022年12月3日周六 00:26写道：

**Comment by zhxacg** [comment]
自己打aar本地包

**Comment by codesdt** [comment]
没理解 我直接把你项目拷贝下来，然后运行就可以测试吗？谢谢

kalu ***@***.***> 于2022年12月5日周一 14:48写道：

**Comment by zhxacg** [comment]
可以

**Comment by codesdt** [comment]
可以了，谢谢，你这个是用的最新版本吗

kalu ***@***.***> 于2022年12月7日周三 12:46写道：

**Comment by zhxacg** [comment]
是的

**Comment by codesdt** [comment]
您那边有遇到这个情况吗？就是rtsp udp 组播 播放 ，播放一会儿就会断流，单播又没事。

kalu ***@***.***> 于2022年12月14日周三 16:02写道：
