### ISSUE TITLE
can you share the aar of the ffmpeg that you are using ?

### ISSUE THREAD

**Issue by AhmedHumk** [kalu-github/module_mediaplayer#6]
i am trying to use your ffmpeg videorenderer can you share the aar of the ffmpeg extension ?

**Comment by zhxacg** [comment]
https://github.com/kalu-github/module_mediaplayer/blob/master/app/libs/lib_mediaplayer_exo_r2.18.2_ff4.4_video_release_20230116.aar

**Comment by AhmedHumk** [comment]
thank you but can you include the aar of android.exoplayer2.ext.ffmpeg only ? 
without the other modules

**Comment by zhxacg** [comment]
https://github.com/kalu-github/module_mediaplayer/blob/master/repo/lib_mediaplayer_core_exo_common.zip

**Comment by AhmedHumk** [comment]
> https://github.com/kalu-github/module_mediaplayer/blob/master/repo/lib_mediaplayer_core_exo_common.zip

Thank you for reply. but i only wanted the ffmpeg ext aar those aar had other modules

**Comment by zhxacg** [comment]
not have

**Comment by AhmedHumk** [comment]
No problem dude i am about to build one have a good day
